apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-indexer-0-pv
  labels:
    app: wazuh-indexer
spec:
  storageClassName: wazuh-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: wazuh
    name: wazuh-indexer-wazuh-indexer-0
  hostPath:
    path: /var/lib/wazuh/indexer
