apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-manager-worker-pv
  labels:
    app: wazuh-worker
spec:
  storageClassName: wazuh-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: wazuh
    name: wazuh-manager-worker-wazuh-manager-worker-0
  hostPath:
    path: /var/lib/wazuh/manager/worker
