apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-manager-master-pv
  labels:
    app: wazuh-master
spec:
  storageClassName: wazuh-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: wazuh
    name: wazuh-manager-master-wazuh-manager-master-0
  hostPath:
    path: /var/lib/wazuh/manager/master
